### ISSUE TITLE
Implement requests for vaccine tracking component

### ISSUE THREAD

**Issue by kamax1226** [kamax1226/vhealth#1]
### Acceptance Criteria:

_**Invoke GET or POST `/api/v1/local-government-units/{lguId}/vaccination-centers/{vcId}/vaccine-supplies` where `lguId` is the organization ID and `vcId` is the vaccination center ID to view or add vaccine supplies**_

 - [ ] Pass the X-Correlation-ID request parameter
 - [ ] Pass the JWT
 - [ ] Invoke GET `/api/v1/vaccines` to retrieve the vaccine information (Pass the X-Correlation-ID request parameter and JWT)

_**Invoke GET or PATCH `/api/v1/local-government-units/{lguId}/vaccination-centers/{vcId}/vaccine-supplies/{supplyId}` where `lguId` is the organization ID, `vcId` is the vaccination center ID and `supplyId` is the vaccine supply ID to view or update the status, receipt and delivery dates**_

 - [ ] Pass the X-Correlation-ID request parameter
 - [ ] Pass the JWT
